export const employees = [
  // Row A
  {
    id: 1,
    name: "Ahmad Yusuf",
    position: "Production Worker",
    section: "Production",
    seat: "A12",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#E6EFFE",
    color2: "#3B82F6",
  },
  {
    id: 2,
    name: "Fatima Khan",
    position: "Assembly Line Worker",
    section: "Assembly",
    seat: "A13",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#F3E8FF",
    color2: "#8B5CF6",
  },
  {
    id: 3,
    name: "Mehmet Ali",
    position: "Packaging Operator",
    section: "Packaging",
    seat: "A14",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#ECFDF5",
    color2: "#10B981",
  },
  {
    id: 4,
    name: "Leyla Ahmadi",
    position: "Warehouse Associate",
    section: "Warehouse",
    seat: "A15",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#FEF3C7",
    color2: "#F59E0B",
  },
  {
    id: 5,
    name: "Hasan Al-Farsi",
    position: "Production Worker",
    section: "Production",
    seat: "A22",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#E6EFFE",
    color2: "#3B82F6",
  },
  {
    id: 6,
    name: "Mariam Zafar",
    position: "Assembly Line Worker",
    section: "Assembly",
    seat: "A23",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#F3E8FF",
    color2: "#8B5CF6",
  },
  {
    id: 7,
    name: "Ibrahim Qasim",
    position: "Packaging Operator",
    section: "Packaging",
    seat: "A24",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#ECFDF5",
    color2: "#10B981",
  },
  {
    id: 8,
    name: "Soraya Jafari",
    position: "Warehouse Associate",
    section: "Warehouse",
    seat: "A25",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#FEF3C7",
    color2: "#F59E0B",
  },

  // Row B
  {
    id: 9,
    name: "Omar Hassan",
    position: "Maintenance Worker",
    section: "Maintenance",
    seat: "B12",
    shift_info: "Kunduzgi smena (14:00 - 22:00)",
    color1: "#FEE2E2",
    color2: "#EF4444",
  },
  {
    id: 10,
    name: "Aisha Mahmoud",
    position: "Logistics Handler",
    section: "Logistics",
    seat: "B13",
    shift_info: "Kunduzgi smena (14:00 - 22:00)",
    color1: "#DBEAFE",
    color2: "#3B82F6",
  },
  {
    id: 11,
    name: "Mustafa Ibrahim",
    position: "Quality Inspector",
    section: "Quality Control",
    seat: "B14",
    shift_info: "Kunduzgi smena (14:00 - 22:00)",
    color1: "#FCE7F3",
    color2: "#EC4899",
  },
  {
    id: 12,
    name: "Zeynep Yilmaz",
    position: "Cleaning Staff",
    section: "Cleaning",
    seat: "B15",
    shift_info: "Kunduzgi smena (14:00 - 22:00)",
    color1: "#E5E7EB",
    color2: "#6B7280",
  },
  {
    id: 13,
    name: "Rashid Abbasi",
    position: "Maintenance Worker",
    section: "Maintenance",
    seat: "B22",
    shift_info: "Kunduzgi smena (14:00 - 22:00)",
    color1: "#FEE2E2",
    color2: "#EF4444",
  },
  {
    id: 14,
    name: "Dalia Haddad",
    position: "Logistics Handler",
    section: "Logistics",
    seat: "B23",
    shift_info: "Kunduzgi smena (14:00 - 22:00)",
    color1: "#DBEAFE",
    color2: "#3B82F6",
  },
  {
    id: 15,
    name: "Zahra Ismail",
    position: "Quality Inspector",
    section: "Quality Control",
    seat: "B24",
    shift_info: "Kunduzgi smena (14:00 - 22:00)",
    color1: "#FCE7F3",
    color2: "#EC4899",
  },
  {
    id: 16,
    name: "Mohammed Al-Rashid",
    position: "Cleaning Staff",
    section: "Cleaning",
    seat: "B25",
    shift_info: "Kunduzgi smena (14:00 - 22:00)",
    color1: "#E5E7EB",
    color2: "#6B7280",
  },

  // Row C
  {
    id: 17,
    name: "Ali Reza",
    position: "Production Worker",
    section: "Production",
    seat: "C12",
    shift_info: "Tungi smena (22:00 - 6:00)",
    color1: "#E6EFFE",
    color2: "#3B82F6",
  },
  {
    id: 18,
    name: "Nour El-Din",
    position: "Assembly Line Worker",
    section: "Assembly",
    seat: "C13",
    shift_info: "Tungi smena (22:00 - 6:00)",
    color1: "#F3E8FF",
    color2: "#8B5CF6",
  },
  {
    id: 19,
    name: "Yasmin Ahmed",
    position: "Packaging Operator",
    section: "Packaging",
    seat: "C14",
    shift_info: "Tungi smena (22:00 - 6:00)",
    color1: "#ECFDF5",
    color2: "#10B981",
  },
  {
    id: 20,
    name: "Karim Nasser",
    position: "Warehouse Associate",
    section: "Warehouse",
    seat: "C15",
    shift_info: "Tungi smena (22:00 - 6:00)",
    color1: "#FEF3C7",
    color2: "#F59E0B",
  },
  {
    id: 21,
    name: "Sami Amir",
    position: "Production Worker",
    section: "Production",
    seat: "C22",
    shift_info: "Tungi smena (22:00 - 6:00)",
    color1: "#E6EFFE",
    color2: "#3B82F6",
  },
  {
    id: 22,
    name: "Leila Najjar",
    position: "Assembly Line Worker",
    section: "Assembly",
    seat: "C23",
    shift_info: "Tungi smena (22:00 - 6:00)",
    color1: "#F3E8FF",
    color2: "#8B5CF6",
  },
  {
    id: 23,
    name: "Nadia Hamid",
    position: "Packaging Operator",
    section: "Packaging",
    seat: "C24",
    shift_info: "Tungi smena (22:00 - 6:00)",
    color1: "#ECFDF5",
    color2: "#10B981",
  },
  {
    id: 24,
    name: "Khalid Bakr",
    position: "Warehouse Associate",
    section: "Warehouse",
    seat: "C25",
    shift_info: "Tungi smena (22:00 - 6:00)",
    color1: "#FEF3C7",
    color2: "#F59E0B",
  },

  // Row D
  {
    id: 25,
    name: "Layla Karimi",
    position: "Maintenance Worker",
    section: "Maintenance",
    seat: "D12",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#FEE2E2",
    color2: "#EF4444",
  },
  {
    id: 26,
    name: "Tariq Aziz",
    position: "Logistics Handler",
    section: "Logistics",
    seat: "D13",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#DBEAFE",
    color2: "#3B82F6",
  },
  {
    id: 27,
    name: "Samira Hakim",
    position: "Quality Inspector",
    section: "Quality Control",
    seat: "D14",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#FCE7F3",
    color2: "#EC4899",
  },
  {
    id: 28,
    name: "Jamal Farooq",
    position: "Cleaning Staff",
    section: "Cleaning",
    seat: "D15",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#E5E7EB",
    color2: "#6B7280",
  },
  {
    id: 29,
    name: "Rania Mahmoud",
    position: "Maintenance Worker",
    section: "Maintenance",
    seat: "D22",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#FEE2E2",
    color2: "#EF4444",
  },
  {
    id: 30,
    name: "Samir Khalid",
    position: "Logistics Handler",
    section: "Logistics",
    seat: "D23",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#DBEAFE",
    color2: "#3B82F6",
  },
  {
    id: 31,
    name: "Laila Nour",
    position: "Quality Inspector",
    section: "Quality Control",
    seat: "D24",
    shift_info: "Ertalabki smena (6:00 - 14:00)",
    color1: "#FCE7F3",
    color2: "#EC4899",
  },

  // Row E
  {
    id: 32,
    name: "Zainab Malik",
    position: "Production Worker",
    section: "Production",
    seat: "E12",
    shift_info: "Kunduzgi smena (14:00 - 22:00)",
    color1: "#E6EFFE",
    color2: "#3B82F6",
  },
  {
    id: 33,
    name: "Youssef Mansour",
    position: "Assembly Line Worker",
    section: "Assembly",
    seat: "E13",
    shift_info: "Kunduzgi smena (14:00 - 22:00)",
    color1: "#F3E8FF",
    color2: "#8B5CF6",
  },
  {
    id: 34,
    name: "Amina Khalil",
    position: "Packaging Operator",
    section: "Packaging",
    seat: "E14",
    shift_info: "Kunduzgi smena (14:00 - 22:00)",
    color1: "#ECFDF5",
    color2: "#10B981",
  },
  {
    id: 35,
    name: "Faisal Rahman",
    position: "Warehouse Associate",
    section: "Warehouse",
    seat: "E15",
    shift_info: "Kunduzgi smena (14:00 - 22:00)",
    color1: "#FEF3C7",
    color2: "#F59E0B",
  },
];

// Color scheme mapping for easy reference:
// Production Workers: Light Blue (#E6EFFE, #3B82F6)
// Assembly Line Workers: Light Purple (#F3E8FF, #8B5CF6)
// Packaging Operators: Light Green (#ECFDF5, #10B981)
// Warehouse Associates: Light Yellow (#FEF3C7, #F59E0B)
// Maintenance Workers: Light Red (#FEE2E2, #EF4444)
// Logistics Handlers: Light Blue (#DBEAFE, #3B82F6)
// Quality Inspectors: Light Pink (#FCE7F3, #EC4899)
// Cleaning Staff: Light Gray (#E5E7EB, #6B7280)
